{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loadpilot.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.monitoring.grafana.adminPassword | b64enc | quote }}
{{- end }}
