apiVersion: v2
name: loadpilot
description: LoadPilot distributed load testing stack — NATS broker + agents + monitoring.
type: application
version: 0.1.0
appVersion: "0.1.7"
keywords:
  - loadpilot
  - load-testing
  - performance
home: https://vladislavakulich.github.io/loadpilot/
sources:
  - https://github.com/VladislavAkulich/loadpilot
